#linear algebra operations
import numpy as np
A = np.array(input("enter the 3*3 matrix A:"))
B=np.array(input("enter the 3*3 matrix B:"))
print "Addition of matrix A and B:\n",np.add(A,B)
print "Subraction of matrix A and B:\n",np.subtract(A,B)
print "Multiplication of matrix A and B:\n",np.matmul(A,B)
print "Division of matrix A and B:\n",np.divide(A,B)
print "Square  of A:\n", np.square(A)
print "Square  of B:\n", np.square(B)
print "Transpose of A:\n", np.transpose(A)
print "Transpose of B:\n", np.transpose(B)
print "Square root matrix of A:\n", np.sqrt(A)
print "Square root matrix of B:\n", np.sqrt(B)
print "Rank of A:", np.linalg.matrix_rank(A)
print "Rank of B:", np.linalg.matrix_rank(B)
print "Trace of A:", np.trace(A)
print "Trace of B:", np.trace(B)
print "Determinant of A:", np.linalg.det(A)
print "Determinant of B:", np.linalg.det(B)
print "Inverse matrix of A:\n", np.linalg.inv(A)
print "Inverse matrix of B:\n", np.linalg.inv(B)
